name: Docker Image CI (day-3)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./day-3
      run: docker build . --file Dockerfile --tag lucdev-aoc-day3:$(date +%s)
